name: Nodejs Package on Dev Version

on:
  push:
    branches:
      - develop

jobs:
  publish:
    if: "contains(github.event.head_commit.message, '[publish dev]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install pnpm -g

      - name: Build TypeScript files
        run: |
          pnpm install
          node ./toolbox/dev-version.mjs
          pnpm run build

      - run: npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
