alternate: testName # 站点大标题

statics: "/" # 静态文件根目录
assets: "assets"
css: "css"
js: "js"

open_graph:
#twitter_id:
#google_plus:
#fb_admins:
#fb_app_id:

grayMode: false # 全站黑白滤镜
# 请注意: 本主题的PWA功能只是一个装载器,需要自备js和manifest
# 图片可通过https://lp-pwa.gitee.io/pwa-genicon/生成
pwa:
  enable: false # 开启PWA功能
  serviceworker: sw.js #serviceworker脚本位置,使用以/为基准的绝对路径
  manifest: manifest.json #manifest位置,使用以/为基准的绝对路径

# 实验性特性
experiments:
  mobileWidth: 820px # 移动版和桌面版导航栏最短切换长度
  copyrightLength: 50 # 自定义复制时显示copyright的长度
  antiFakeWebsite: true # 防止恶意网站伪装

homeConfig:
  gradient: false # 使用CSS渐变作为文章封面
  # fixedCover 性能比默认的更好，且开启时将启用LCP优化和预加载
  fixedCover: "" # 主页面cover(为空则使用bing随机图片)
  coverConfig:
    enableCover: true # 是否开启头图
    enablePreload: true #是否开启预加载头图
    enableNextGradientCover: false # 使用CSS渐变作为上/下一页封面
  cateCards:
    - slug: # 分类 slug
      cover: # 分类封面

# ShokaX 模块化分包引入设置
# 请关闭所有不使用的模块以优化主题 js 体积和性能
modules:
  debug: false # 启用调试模式
  player: true # 启用音乐播放器
  fireworks: true # 启用鼠标点击烟花特效
  visibilityListener: true # 启用可见度监听器，当你不需要页面标题随标签页切换而变化可关闭
  tabs: true # 启用选项卡扩展支持，如需开启 summary 功能请一并开启
  quiz: true # 启用文章内问题扩展支持
  # 使用 Cloudflare Rocket 或其他优化功能时需开启下列补丁，否则主题无法渲染
  cloudflarePatch: false

# 优化性能区
performance:
  # 使用preconnect预加载的网址(不建议超过三个)
  preConnect:
    - "https://s4.zstatic.net"
    - "https://at.alicdn.com"
  # 使用dns-prefetch预解析的网址
  dnsPrefetch:

playerAPI: "https://api.injahow.cn" # 结尾不带/,只填写域名
# 如果条件允许,请参考 https://github.com/injahow/meting-api 自建API
# 使用vercel自行部署,请参考: https://github.com/xizeyoupan/Meting-API

icon:
  favicon: "/favicon.ico"
  apple_touch_icon: "/apple-touch-icon.png"

seo:
  bing:
  google:
  yandex:
  baidu:

visitor:
  clarity: false
  baiduAnalytics: false
  googleAnalytics: false

darkmode: true
auto_dark: # 自动亮/暗模式
  enable: true #是否开启
  start: 20 #开始时间
  end: 7 #结束时间

auto_scroll: false

loader:
  start: true # 进入页面时显示加载动画
  switch: false # 切换页面时显示加载动画

# 显示的动画(烟花)
# 参阅 https://github.com/D-Sketon/mouse-firework
fireworks:
  enable: true
  options:
    excludeElements: ["a"]
    particles:
      - shape: circle
        move: ["emit"]
        easing: easeOutExpo
        colors:
          - "rgba(255,182,185,.9)"
          - "rgba(250,227,217,.9)"
          - "rgba(187,222,214,.9)"
          - "rgba(138,198,209,.9)"
        number: 30
        duration: [1200, 1800]
        shapeOptions:
          radius: [16, 32]
      - shape: circle
        move: ["diffuse"]
        easing: easeOutExpo
        colors: ["#fff"]
        number: 1
        duration: [1200, 1800]
        shapeOptions:
          radius: 20
          alpha: 0.5
          lineWidth: 6

font:
  enable: true
  # 从google字体库加载,如果自定义@font-face请关闭
  loadFromGoogle: true
  # 字体选项:
  # `external`:从google字体库加载字体.
  # `family: 字体家族名,无需引号
  # `size: x.x`. 以`em`为单位. 默认: 1 (16px)

  # 适用于所有在body标签内的文字.
  global:
    external: true
    family: Mulish
    size:

  # 大标题字体.
  logo:
    external: true
    family: Fredericka the Great
    size: 3.5

  # 页面标题字体.
  title:
    external: true
    family: Noto Serif JP
    size: 2.5

  # 标题字体.
  headings:
    external: true
    family: Noto Serif SC
    size:

  # 文章字体.
  posts:
    external: false
    family:

  # 代码块的字体
  codes:
    external: true
    family: Inconsolata

# //at.alicdn.com/t/c/font_4415496_59g1326wajd.css => 4415496_59g1326wajd
# 自定义iconfont图标参见文档教程
iconfont: "4415496_59g1326wajd"

menu:
  home: / || home
  # about:
  #   default: / || user
  #   aboutsite: /about/  || user
  #   admiration: /admiration/ || coffee
  # posts:
  #   default: / || feather
  #   archives: /archives/ || list-alt
  #   categories: /categories/ || th
  #   tags: /tags/ || tags
  # friends: /friends/ || heart

# https://twikoo.js.org
twikoo:
  enable: false
  mode: vercel # vercel或tencent
  envId: "https://example.com" # twikoo环境ID,vercel填地址
  region:

# https://waline.js.org/
waline:
  enable: false
  serverURL: ""
  lang: "zh-CN"
  locale: {} # https://waline.js.org/guide/features/i18n.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80
  emoji: # 表情包
    # - https://unpkg.com/@waline/emojis@1.0.1/weibo
    # - https://unpkg.com/@waline/emojis@1.0.1/alus
    # - https://unpkg.com/@waline/emojis@1.0.1/bilibili
    # - https://unpkg.com/@waline/emojis@1.0.1/qq
    # - https://unpkg.com/@waline/emojis@1.0.1/tieba
    # - https://unpkg.com/@waline/emojis@1.0.1/tw-emoji
  meta: # 可以填写的内容
    - nick
    - mail
    - link
  requiredMeta: # 必须填写的内容
    - nick
    - mail
  wordLimit: 0 # 字数限制,0为不限制
  pageSize: 10 # 每页评论条数
  pageview: false # 是否开启浏览量统计,可独立开启
  recaptchaV3Key: # reCAPTCHA v3密钥
  turnstileKey: # Turnstile密钥

summary:
  enable: false
  introduce: "" # AI自我介绍
  model:
  apiKey:
  apiUrl:
  temperature:
  initalPrompt:
  concurrency: 5

# 由于 Hexo 的 ESM 模块支持存在严重缺陷，ShokaX 无法引入自动索引流程，Pagefind 构建需要通过 CLI 手动执行
# 在每次 generate 完成后需要执行`pnpm dlx pagefind --site public`，再 deploy，否则 Pagefind 无法正常工作
# 参见：https://docs.shokax.kaitaku.xyz/features/search/#pagefind-%E6%90%9C%E7%B4%A2
pagefind: # pagefind 本地搜索 https://pagefind.app/
  enable: false # 是否启用


# Social Links
# Usage: `Key: permalink || icon || color`
# Key is the link label showing to end users.
# Value before `||` delimiter is the target permalink,
# secend value is the name of Font icon.
social:
  github: https://github.com/yourname || github || "#191717"
  #gitee: https://gitee.com/yourname || gitee || "#e60026"
  #google: https://plus.google.com/yourname || google
  #twitter: https://twitter.com/yourname || twitter || "#00aff0"
  #zhihu: https://www.zhihu.com/people/yourname || zhihu || "#1e88e5"
  #music: https://music.163.com/#/user/home?id=yourid || cloud-music || "#e60026"
  #weibo: https://weibo.com/yourname || weibo || "#ea716e"
  #about: https://about.me/yourname || address-card || "#3b5998"
  #email: mailto:foo@xxx.com || envelope || "#55acd5"
  #facebook: https://www.facebook.com/yourname || facebook
  #stackoverflow: https://stackoverflow.com/ || stack-overflow
  #youtube: https://youtube.com/yourname || youtube
  #instagram: https://instagram.com/yourname || instagram
  #skype: skype:yourname?call|chat || skype
  #douban: https://www.douban.com/people/yourname/ || douban

sidebar:
  # Sidebar Position.
  position: left
  # position: right
  # Replace the default avatar image under <root>/source/_data/assets/ and set the url here.
  avatar: avatar.jpg

widgets:
  # if true, will show random posts
  random_posts: true
  # if true, will show recent comments
  recent_comments: true

footer:
  # Specify the date when the site was set up. If not defined, current year will be used.
  since: 2022
  icon:
    name: sakura rotate
    # Change the color of icon, using Hex Code.
    color: "#ffc0cb"
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  count: true
  powered: true
  icp: # ICP备案
    enable: false
    # 请在登录后从 https://beian.mps.gov.cn/web/business/businessHome/website 下载对应图标
    icon: "" #网安备案图片
    icpnumber: "xxx" # ICP备案号
    beian: "xxx" # 网安备案号
    recordcode: "xxx" # 网安备案链接中的recordcode参数

post:
  count: true

# 文章是否失效
outime:
  enable: false
  days: 90 # 超过 90 天文章失效

reward:
  # If true, reward will be displayed in every article by default.
  enable: true
  account:
    wechatpay: /wechatpay.png
    alipay: /alipay.png
    # paypal: /paypal.png

# TagCloud settings for tags page.
tagcloud:
  # All values below are same as default, change them by yourself.
  min: 16 # Minimun font size in px
  max: 22 # Maxium font size in px
  start: "#72cecf" # Start color (hex, rgba, hsla or color keywords)
  end: "#ffbac3" # End color (hex, rgba, hsla or color keywords)
  amount: 200 # Amount of tags, change it if you have more than 200 tags

# ---------------------------------------------------------------
# Third Party Plugins & Services Settings
# ---------------------------------------------------------------

# Creative Commons 4.0 International License.
# See: https://creativecommons.org/share-your-work/licensing-types-examples
# Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# You can set a language value if you prefer a translated version of CC license, e.g. deed.zh
# CC licenses are available in 39 languages, you can find the specific and correct abbreviation you need on https://creativecommons.org
creative_commons:
  license: by-nc-sa
  language: deed.zh

# bgm
audio:
#  - title: 列表1
#    list:
#      - https://music.163.com/#/playlist?id=2943811283
#  - title: 列表2
#    list:
#      - https://music.163.com/#/playlist?id=2031842656

# Algolia Search
# For more information: https://www.algolia.com
search:
  hits:
    per_page: 10

#! ---------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING `vendors` SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! ---------------------------------------------------------------
vendors:
  cdns:
    cdnjs: https://s4.zstatic.net/ajax/libs
  js:
  async_js:
    copy_tex:
      source: cdnjs
      url: KaTeX/0.16.9/contrib/copy-tex.min.js
      sri: "sha384-ww/583aHhxWkz5DEVn6OKtNiIaLi2iBRNZXfJRiY1Ai7tnJ9UXpEsyvOITVpTl4A"
  css:
    katex:
      source: cdnjs
      url: KaTeX/0.16.9/katex.min.css
      sri: "sha384-n8MVd4RsNIU0tAv4ct0nTaAbDJwPJzDEaqSD1odI+WdtXRGWt2kTvGFasHpSy3SV"
